name: publish Ardalis.HttpClientTestExtensions to nuget
on:
  push:
    branches:
      - main # Your default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Ardalis.HttpClientTestExtensions.sln'

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore dependencies
        run: nuget restore $SOLUTION  

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
          
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      #- name: Run tests
      #  run: dotnet test --no-restore --no-build --verbosity normal
        
      # Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Ardalis.HttpClientTestExtensions/Ardalis.HttpClientTestExtensions.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
